name: Enviar Print do Looker para SeaTalk

on:
  schedule:
    # Executa de segunda a sexta-feira às 07:30 UTC (Ajuste o cron conforme sua preferência de horário)
    - cron: '30 7 * * 1-5'
  workflow_dispatch: # Permite disparar manualmente direto pela aba Actions do GitHub

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Executar o Bot
        env:
          LOOKER_URL: https://datastudio.google.com/u/0/reporting/381b9841-a980-41cb-9a7d-a7216bad7518/page/p_cm7j7npe2d
          SEATALK_WEBHOOK_URL: ${{ secrets.SEATALK_WEBHOOK_URL }}
        run: |
          python bot.py
